[tool.poetry]
name = "codecov-demo"
version = "0.1.0"
description = ""
authors = ["AABur <aabur@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.1.1"

[tool.poetry.dev-dependencies]
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
