name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    defaults:
      run:
        working-directory: ./api
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov .
    - name: Upload coverage reports to Codecov with GitHub Action
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      run: | 
       curl -Os https://uploader.codecov.io/latest/linux/codecov
       find . -iregex "codecov.*"
       chmod +x codecov 
       ./codecov -t ${CODECOV_TOKEN}
      # uses: codecov/codecov-action@v3